# This is the config file for Prettier.
# See CODING-STYLE.md for more information.

# NOTE: If you are using prettier-atom you must restart atom for any changes
# made here to take effect. The prettier-atom plugin only reads this config file
# once and then caches it. It will not detect changes.

# Use larger indentions to make code blocks easier to see.
tabWidth: 4
useTabs: true

# Put a trailing comma in multi-line objects and arrays so that fields can be
# added with out having to edit the line above.
trailingComma: "es5"

overrides:
    # Use prose wrapping to make Markdown documents more readable when displayed as
    # plain text.
    - files: "*.md"
      options:
          proseWrap: "always"
    # The Markdown format requires space intentions and YAML considers them invalid
    # characters.
    - files: "*.{md,yaml,yml}"
      options:
          useTabs: false
    - files: "*.{yaml,yml}"
      options:
          tabWidth: 2

# All other options are left at their default values.
