language: node_js
node_js:
  - 8
cache:
  directories:
  - node_modules
  - $HOME/.meteor
  - .meteor/local
before_install:
  - export PATH=$HOME/.meteor:$PATH
install:
  - npm install
  - ./install-meteor
script:
  - npm run lint
  - npm run lint-formatting
  - npm run type-check
  - meteor test --once --driver-package meteortesting:mocha
