language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: "Linting"
      name: "Eslint"
      script: "npm run lint"
    - name: "Prettier"
      script: "npm run lint-formatting"
    - name: "Flow type check"
      script: "npm run type-check"
