language: node_js
node_js:
  - "8"
jobs:
  include:
    - stage: "Linting"
      name: "Eslint"
      script: "npm run lint"
    - script: "npm run lint-formatting"
      name: "Prettier"
    - script: "npm run type-check"
      name: "Flow type check"
