language: node_js
node_js:
  - 8
cache:
  directories:
  - node_modules
  - $HOME/.meteor
  - .meteor/local
jobs:
  include:
    - stage: prepair cache
      install:
        - npm install
        - ./install-meteor
      script: true
    - stage: lint and test
      name: eslint
      install: true
      script: npm run lint
    - name: prettier
      install: true
      script: npm run lint-formatting
    - name: flow type check
      install: true
      script: npm run type-check
    - name: meteor and mocha tests
      install: true
      script: meteor test --once --driver-package meteortesting:mocha
