language: node_js
node_js:
  - 8
cache:
  directories:
  - node_modules
  - $HOME/.meteor
  - .meteor/local
jobs:
  include:
    - stage: Prepair NPM cache
      script: true
    - stage: Linting
      name: Eslint
      install: true
      script: npm run lint
    - name: Prettier
      install: true
      script: npm run lint-formatting
    - name: Flow type check
      install: true
      script: npm run type-check
    - stage: Install meteor
      install: "curl 'https://install.meteor.com?release=1.6.1.1' | /bin/sh"
      script: true
    - stage: Unit tests
      install: true
      script: meteor test --once --driver-package meteortesting:mocha
