version: "3"
services:
  web:
    build:
      context: ./meteor-app
      dockerfile: Dockerfile
    image: vize-meteor-dev
    ports:
      - "3000:3000"
    environment:
      NODE_UID: "${NODE_UID}"
      NODE_GID: "${NODE_GID}"
    volumes:
      - # Allow meteor to read the project's source code.
        # This is done as a volume instead of COPY so that
        # Meteor can live reload as you edit the source code.
        "./meteor-app:/home/node/meteor/src"
      - meteor-dotfile:/home/node/.meteor
volumes:
  # Meteor's dotfile where meteor is installed and caches its packages. Meteor
  # downloads and creates a lot of files. We store this data in a volume so that
  # is does not need to be redownloaded and duplicated any more than nessisary.
  meteor-dotfile:
