version: "3"
services:
  web:
    build:
      context: ./meteor-app
      dockerfile: Dockerfile
    image: vize-meteor-dev
    ports:
      - "3000:3000"
    volumes:
      - # Allow meteor to read the project's source code.
        # This is done as a volume instead of COPY so that
        # Meteor can live reload as you edit the source code.
        "./meteor-app:/home/node/meteor/src"
      - meteor-dotfile:/home/node/.meteor
    environment:
      NODE_UID: "${NODE_UID}"
      NODE_GID: "${NODE_GID}"
      MONGO_URL: mongodb://mongo:27017/meteor
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: meteor
      PGPASSWORD: "123456789"
      PGDATABASE: meteor
    depends_on:
      - mongo
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
  flyway:
    image: boxfuse/flyway:5.2.1
    command: -url=jdbc:postgresql://postgres:5432/meteor -user=meteor -password=123456789 -connectRetries=60 migrate
    volumes:
      - ./postgres/migrations:/flyway/sql
    depends_on:
      - postgres
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    deploy:
      restart_policy:
        condition: on-failure
  postgres:
    build: ./postgres
    image: vize-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: meteor
      POSTGRES_PASSWORD: "123456789"
      POSTGRES_DB: meteor
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  # These database volumes ensure that the data in the databases is durable and
  # persistaint (ie. does not get deleted every so often).
  # NOTE: If you need to start fresh (eg. test out the init scripts or
  # delete all data) just delete these "*-data" volumes and rerun this stack.
  mongo-data:
  postgres-data:
  # Meteor's dotfile where meteor is installed and caches its packages. Meteor
  # downloads and creates a lot of files. We store this data in a volume so that
  # is does not need to be redownloaded and duplicated any more than nessisary.
  meteor-dotfile:
