version: "3"
services:
  web:
    build:
      context: ./meteor-app
      dockerfile: Dockerfile-dev
    image: vize-meteor-dev
    ports:
      - "3000:3000"
    volumes:
      - # Allow meteor to read the project's source code.
        # This is done as a volume instead of COPY so that
        # Meteor can live reload as you edit the source code.
        # Make this read only because the build should not change the src.
        "./meteor-app:/home/node/meteor/src:ro"
      - # Use these volumes to cache builds and dependencies.
        # NOTE: These can not automaticaly make their own mount points because
        #       the parent volume is read-only. If you get errors when starting
        #       this sevice, try creating the directories
        #       `meteor-app/node_modules` and `meteor-app/.meteor/local`.
        #       It does not matter what is inside them, they just need to exist.
        meteor-local:/home/node/meteor/src/.meteor/local
      - meteor-dotfile:/home/node/.meteor
      - meteor-app-modules:/home/node/meteor/src/node_modules
volumes:
  # Meteor build caches. Meteor and NPM download and create a lot of files.
  # We store this data in volumes so that is does not need to be redownloaded
  # and duplicated any more than nessisary.

  # Meteor's cache of build artifacts. Allows for faster rebuilds.
  meteor-local:

  # Meteor's dotfile where meteor is installed and caches its packages.
  meteor-dotfile:

  meteor-app-modules:
