version: "3"
services:
  web-dev:
    build: ./meteor-dev
    image: vize-meteor-dev
    ports:
      - "3000:3000"
    volumes:
        # Allow meteor to read the project's source code.
        # Make this read only because the build should not change the src.
      - "./meteor-app:/opt/meteor/src:ro"
        # Use these volumes to cache builds and dependencies.
      - node-modules:/opt/meteor/src/node_modules
      - meteor-local:/opt/meteor/src/.meteor/local
        # Meteor is stupid and tries to delete and move around it's dotfile
        # during installation. So we are forced to volume the whole home
        # directory.
      - meteor-dotfile:/root
    environment:
      MONGO_URL: mongodb://mongo:27017/meteor
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: meteor
      PGPASSWORD: "123456789"
      PGDATABASE: meteor
    depends_on:
      - mongo
      - postgres
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: meteor
      POSTGRES_PASSWORD: "123456789"
      POSTGRES_DB: meteor
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
volumes:
  mongo-data:
  postgres-data:
  node-modules:
  meteor-local:
  meteor-dotfile:
