version: "3"
services:
  flyway:
    image: boxfuse/flyway:5.2.1
    command: -url=jdbc:postgresql://postgres:5432/meteor -user=meteor -password=123456789 -connectRetries=60 migrate
    volumes:
      - ./postgres/migrations:/flyway/sql
    depends_on:
      - postgres
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    deploy:
      restart_policy:
        condition: on-failure
  postgres:
    build: ./postgres
    image: vize-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: meteor
      POSTGRES_PASSWORD: "123456789"
      POSTGRES_DB: meteor
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  # These database volumes ensure that the data in the databases is durable and
  # persistaint (ie. does not get deleted every so often).
  # NOTE: If you need to start fresh (eg. test out the init scripts or
  # delete all data) just delete these "*-data" volumes and rerun this stack.
  mongo-data:
  postgres-data:
