version: "3"
services:
  web:
    build: .
    image: vize-meteor
    ports:
      - "80:80"
    environment:
      MONGO_URL: "mongodb://mongo:27017/meteor"
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
volumes:
  data-volume:
