---
- hosts: all
  remote_user: joshua
  become: yes
  become_method: sudo
  tasks:
    - name: Install PostgreSQL
      apt: pkg={{ item }} state=present
      with_items:
        - postgresql-10
        - python-psycopg2

    - name: Create the vize database
      become_user: postgres
      postgresql_db:
        name: vize

    - name: Add me as a DB user
      become_user: postgres
      postgresql_user:
        db: vize
        name: joshua
        password: test123
        encrypted: yes
        priv: "ALL"
        expires: infinity

    - name: Install MongoDB
      apt: pkg=mongodb-server state=present
